### ISSUE TITLE
Content of comments not being saved

### ISSUE THREAD

**Issue by loglow** [Radiquum/furaffinity-dl#5]
All the comments in the downloaded metadata were showing up blank, like:

    "content": "",

I changed line 229 in download.py from:

    "content": comment.find(class_="comment_text").contents[0].strip(),

To:

    "content": comment.find(class_="user-submitted-links").text.strip(),

And now the content of each comment is showing up correctly.

**Comment by Radiquum** [comment]
Thank you for the contribution. I have pushed it to the python branch. Please let me know if something else is working not as expected, since I didn't really use it as much myself anymore.
