### ISSUE TITLE
Unable to find next button when downloading favourites

### ISSUE THREAD

**Issue by 4KGAMECUBE** [Radiquum/furaffinity-dl#6]
Not sure if I am being dumb or or the FA website has changed however when trying to download my favourites, it downloads a page and then is unable to move onto the next one with the console saying "Unable to find next button". It seems to work absolutely fine for galleries but not for favourites. Hopefully it can be sorted out!

**Comment by Radiquum** [comment]
Hello again, I pushed a possible fix to the main (python) branch, can you try it now and give a feedback if that has been fixed?

**Comment by 4KGAMECUBE** [comment]
I shall in a bit when I have time!

**Comment by 4KGAMECUBE** [comment]
Seems fine to me!

**Comment by Radiquum** [comment]
> Seems fine to me!

glad to hear that. If something else is wrong, feel free to open a new issue :3
