### ISSUE TITLE
SyntaxError: f-string: unmatched '['

### ISSUE THREAD

**Issue by RemiSterling** [Radiquum/furaffinity-dl#8]
Attempting to run the python3 furaffinity-dl.py for favorites, with a cookie file I am seeing the following:

Traceback (most recent call last):
  File "/home/jurrel/Pictures/FA-Favs-Downloads/furaffinity-dl-python/furaffinity-dl.py", line 9, in <module>
    from Modules.download import download
  File "/home/jurrel/Pictures/FA-Favs-Downloads/furaffinity-dl-python/Modules/download.py", line 9, in <module>
    from Modules.functions import DownloadComplete
  File "/home/jurrel/Pictures/FA-Favs-Downloads/furaffinity-dl-python/Modules/functions.py", line 144
    page_num = f"{parse_next_button.parent.attrs["action"].split("/")[-2]}/next"
                                                                                          ^^^^^^   ##Broken spacing, this is under "action"##
SyntaxError: f-string: unmatched '['

Using Python 3.10.12

**Comment by Radiquum** [comment]
Hello, can you provide username for which this is happening? Also, do you use modern theme?

**Comment by RemiSterling** [comment]
Sure under jurrel and yes I am using modern layout, dark theme.
![Screenshot from 2024-11-15 15-40-24](https://github.com/user-attachments/assets/b2e2551c-0607-4b6a-8927-ecf54a303062)

**Comment by Radiquum** [comment]
hmm, strange, it seems to work fine for me. What command did you use? And in what page number does it happen?

I tried with this command: `python .\furaffinity-dl.py jurrel favorites  --dry -c .\cookies.txt`

**Comment by RemiSterling** [comment]
I am getting it as soon as I run the command.  Attaching here everything from the command prompt:

python3 furaffinity-dl.py jurrel favorites -c www.furaffinity.net_cookies.txt 
Traceback (most recent call last):
  File "/home/jurrel/Pictures/FA-Favs-Downloads/furaffinity-dl-python/furaffinity-dl.py", line 9, in <module>
    from Modules.download import download
  File "/home/jurrel/Pictures/FA-Favs-Downloads/furaffinity-dl-python/Modules/download.py", line 9, in <module>
    from Modules.functions import DownloadComplete
  File "/home/jurrel/Pictures/FA-Favs-Downloads/furaffinity-dl-python/Modules/functions.py", line 144
    page_num = f"{parse_next_button.parent.attrs["action"].split("/")[-2]}/next"
                                                  ^^^^^^
SyntaxError: f-string: unmatched '['

I tried your command and got the same error, this is on linux, not that it should make a difference.

For what it is worth, I used an older version of this scripting before and it would work, but only ever get page 1 of favorites then say it could not find the next button.

**Comment by Radiquum** [comment]
ooh, I maybe understand why that is happening. It seems like on python 3.12 double quotes inside double quotes are working fine, but in older versions like 3.10 they are not. I will try to replace them with single quotes, and give it another try, should be fixed shortly

**Comment by Radiquum** [comment]
Can you update and try it again?

**Comment by RemiSterling** [comment]
That was it!  It is now pulling properly for several pages.

**Comment by Radiquum** [comment]
Thanks for the issue. And sorry I didn't catch it sooner
